import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout (
  { children }: { children: React.ReactNode }
) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <main className='grid min-h-screen grid-rows-[60px,1fr,60px] px-4 max-w-screen-lg'>
          <nav className='flex items-center text-2xl'>Miudlibritos</nav>
          <section>{children}</section>
          <footer className='flex items-center justify-center'>Goncy</footer>
        </main>
      </body>
    </html>
  )
}
